//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/sebas/RiderProjects/DslPresentation/DslPresentation/Grammar\DslParser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IDslParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class DslParserBaseListener : IDslParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DslParser.dsl_batch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDsl_batch([NotNull] DslParser.Dsl_batchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DslParser.dsl_batch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDsl_batch([NotNull] DslParser.Dsl_batchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DslParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScript([NotNull] DslParser.ScriptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DslParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScript([NotNull] DslParser.ScriptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DslParser.get_all"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGet_all([NotNull] DslParser.Get_allContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DslParser.get_all"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGet_all([NotNull] DslParser.Get_allContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DslParser.get_simple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGet_simple([NotNull] DslParser.Get_simpleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DslParser.get_simple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGet_simple([NotNull] DslParser.Get_simpleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DslParser.then_logic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThen_logic([NotNull] DslParser.Then_logicContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DslParser.then_logic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThen_logic([NotNull] DslParser.Then_logicContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DslParser.built_in_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBuilt_in_function([NotNull] DslParser.Built_in_functionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DslParser.built_in_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBuilt_in_function([NotNull] DslParser.Built_in_functionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DslParser.send_email"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSend_email([NotNull] DslParser.Send_emailContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DslParser.send_email"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSend_email([NotNull] DslParser.Send_emailContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DslParser.end_script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnd_script([NotNull] DslParser.End_scriptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DslParser.end_script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnd_script([NotNull] DslParser.End_scriptContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
