//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/sebas/RiderProjects/DslPresentation/DslPresentation/Grammar\DslParser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DslParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IDslParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DslParser.dsl_batch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDsl_batch([NotNull] DslParser.Dsl_batchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DslParser.dsl_batch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDsl_batch([NotNull] DslParser.Dsl_batchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DslParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScript([NotNull] DslParser.ScriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DslParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScript([NotNull] DslParser.ScriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DslParser.get_all"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGet_all([NotNull] DslParser.Get_allContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DslParser.get_all"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGet_all([NotNull] DslParser.Get_allContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DslParser.get_simple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGet_simple([NotNull] DslParser.Get_simpleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DslParser.get_simple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGet_simple([NotNull] DslParser.Get_simpleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DslParser.then_logic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThen_logic([NotNull] DslParser.Then_logicContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DslParser.then_logic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThen_logic([NotNull] DslParser.Then_logicContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DslParser.built_in_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuilt_in_function([NotNull] DslParser.Built_in_functionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DslParser.built_in_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuilt_in_function([NotNull] DslParser.Built_in_functionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DslParser.send_email"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSend_email([NotNull] DslParser.Send_emailContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DslParser.send_email"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSend_email([NotNull] DslParser.Send_emailContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DslParser.end_script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnd_script([NotNull] DslParser.End_scriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DslParser.end_script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnd_script([NotNull] DslParser.End_scriptContext context);
}
